FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY utils/ ./utils/
COPY log/ ./log/

COPY . .

WORKDIR /app/app

ENV PYTHONPATH=/app

CMD ["python", "app/manager.py"]